name: connections-workshop
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - aiohttp=3.8.3
  - fsspec=2023.1.0
  - jupyter
  - pip
  - scikit-learn=1.2.1
  - scikit-image=0.19.3
  - tensorflow=2.10.0
  - tensorflow-cpu=2.10.0
  - pip:
    - intake==0.6.5
    - intake-xarray==0.6.0
    - scivision==0.7.0
